
import './globals.css'
import type { Metadata } from 'next'
import { headers } from 'next/headers'
import { cookieToInitialState } from 'wagmi'
import Header from './components/header'
import { config } from '@/auth/wagmi/config/config'
import { Providers } from '@/auth/wagmi/providers'
import { ReactNode } from 'react'
import {NextUIProvider} from '@nextui-org/react'
import { Montserrat } from "next/font/google";
import Footer from './components/Footer'



const montserrat = Montserrat({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}



export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode,
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <html className='dark' lang="en">
      <body className={montserrat.className}>
        <div className="flex flex-col min-h-screen">
          <Providers initialState={initialState}>
            <NextUIProvider>
              <Header />
              <main className='text-foreground'>
                {children}
              </main>
              <Footer/>
            </NextUIProvider>
          </Providers>
        </div>
      </body>
    </html>
  )
}
