
import './globals.css'
import type { Metadata } from 'next'
import { headers } from 'next/headers'

import { cookieToInitialState } from 'wagmi'

import { config } from '../auth/wagmi/config'
import Web3ModalProvider from '../auth/wagmi/context'
// import Link from 'next/link'
import Header from './components/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  auth
}: Readonly<{
  children: React.ReactNode,
  auth: React.ReactNode
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <html lang="en">
      <body className="flex-1">
        <div className="flex flex-col min-h-screen">

          <Web3ModalProvider initialState={initialState}>
            <Header />
            {children}
          </Web3ModalProvider>
        </div>

      </body>
    </html>
  )
}